// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALHJHhB5zgUpmBKw_GfQMpjmfF8w_bTbY',
    appId: '1:898174421029:web:248dadf005bd5c392a57cc',
    messagingSenderId: '898174421029',
    projectId: 'ecommerceapp-a87c8',
    authDomain: 'ecommerceapp-a87c8.firebaseapp.com',
    storageBucket: 'ecommerceapp-a87c8.firebasestorage.app',
    measurementId: 'G-KYPV37PWCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFZR63KjyTrhgraH7Db_vCCK8eGD8YD-k',
    appId: '1:898174421029:android:227363edd8b3117f2a57cc',
    messagingSenderId: '898174421029',
    projectId: 'ecommerceapp-a87c8',
    storageBucket: 'ecommerceapp-a87c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzNm-EPn5jlzWFvLyp_q1SeneR71v6Ls',
    appId: '1:898174421029:ios:325fe95e00bed07f2a57cc',
    messagingSenderId: '898174421029',
    projectId: 'ecommerceapp-a87c8',
    storageBucket: 'ecommerceapp-a87c8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzNm-EPn5jlzWFvLyp_q1SeneR71v6Ls',
    appId: '1:898174421029:ios:325fe95e00bed07f2a57cc',
    messagingSenderId: '898174421029',
    projectId: 'ecommerceapp-a87c8',
    storageBucket: 'ecommerceapp-a87c8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALHJHhB5zgUpmBKw_GfQMpjmfF8w_bTbY',
    appId: '1:898174421029:web:22674ac8724d83102a57cc',
    messagingSenderId: '898174421029',
    projectId: 'ecommerceapp-a87c8',
    authDomain: 'ecommerceapp-a87c8.firebaseapp.com',
    storageBucket: 'ecommerceapp-a87c8.firebasestorage.app',
    measurementId: 'G-F52VSWH8V1',
  );
}
